# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: '../vendor/beberlei/doctrineextensions/config/mysql.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    router.request_context.scheme: '%env(string:ROUTE_PROTOCOL)%'
    router.request_context.host: '%env(string:ROUTE_HOST)%'
    router.request_context.base_url: '%env(string:ROUTE_BASE)%'

    asset.request_context.base_path: '%env(string:ROUTE_BASE)%'
    asset.request_context.secure: auto

    dhil.piwik_enabled: '%env(bool:PIWIK_ENABLED)%'
    dhil.piwik_url: ~
    dhil.piwik_siteid: ~
    dhil.piwik_domain: ~

    dm.image.dir: '%env(string:DM_IMAGE_DIR)%'
    dm.thumb.width: 450
    dm.thumb.height: 350
    dm.geonames.username: '%env(string:DM_GEONAMES_USERNAME)%'

    # pagination
    page_size: 24
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments', 'knp_paginator.injectable']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\ImageListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }

    App\EventListener\PeriodListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    App\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main}

    App\Services\FileUploader:
        arguments:
            $root: '%kernel.project_dir%'
        calls:
            - [ setUploadDir, [ '%dm.image.dir%/%kernel.environment%'] ]

    App\Services\Thumbnailer:
        calls:
            - [ setHeight, [ '%dm.thumb.height%' ] ]
            - [ setWidth, [ '%dm.thumb.width%' ] ]
